/*
This file was generated and should not be modified directly
*/
using Bam.Net.Data;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Bam.Net.CoreServices.ApplicationRegistration.Data.Dao.Repository
{
    public interface IApplicationRegistrationRepository
    {
        IEnumerable<ActiveApiSigningKeyIndex> ActiveApiKeyIndexsWhere(WhereDelegate<ActiveApiKeyIndexColumns> where, OrderBy<ActiveApiKeyIndexColumns> orderBy = null);
        void AddType(Type type);
        IEnumerable<ApiHmacKey> ApiKeysWhere(WhereDelegate<ApiKeyColumns> where, OrderBy<ApiKeyColumns> orderBy = null);
        IEnumerable<Data.Application> ApplicationsWhere(WhereDelegate<ApplicationColumns> where, OrderBy<ApplicationColumns> orderBy = null);
        Task BatchAllActiveApiKeyIndexs(int batchSize, Action<IEnumerable<ActiveApiSigningKeyIndex>> batchProcessor);
        Task BatchAllApiKeys(int batchSize, Action<IEnumerable<ApiHmacKey>> batchProcessor);
        Task BatchAllApplications(int batchSize, Action<IEnumerable<Data.Application>> batchProcessor);
        Task BatchAllClients(int batchSize, Action<IEnumerable<Data.Client>> batchProcessor);
        Task BatchAllClientServerConnections(int batchSize, Action<IEnumerable<Data.ClientServerConnection>> batchProcessor);
        Task BatchAllConfigurations(int batchSize, Action<IEnumerable<Data.Configuration>> batchProcessor);
        Task BatchAllConfigurationSettings(int batchSize, Action<IEnumerable<Data.ConfigurationSetting>> batchProcessor);
        Task BatchAllHostAddresses(int batchSize, Action<IEnumerable<Data.HostAddress>> batchProcessor);
        Task BatchAllHostDomains(int batchSize, Action<IEnumerable<Data.HostDomain>> batchProcessor);
        Task BatchAllMachines(int batchSize, Action<IEnumerable<Data.Machine>> batchProcessor);
        Task BatchAllNics(int batchSize, Action<IEnumerable<Data.Nic>> batchProcessor);
        Task BatchAllOrganizations(int batchSize, Action<IEnumerable<Data.Organization>> batchProcessor);
        Task BatchAllProcessDescriptors(int batchSize, Action<IEnumerable<Data.ProcessDescriptor>> batchProcessor);
        Task BatchAllSubscriptions(int batchSize, Action<IEnumerable<Data.Subscription>> batchProcessor);
        Task BatchAllUsers(int batchSize, Action<IEnumerable<Data.User>> batchProcessor);
        Task BatchAllUserSettings(int batchSize, Action<IEnumerable<Data.UserSetting>> batchProcessor);
        Task BatchQueryActiveApiKeyIndexs(int batchSize, WhereDelegate<ActiveApiKeyIndexColumns> where, Action<IEnumerable<ActiveApiSigningKeyIndex>> batchProcessor);
        Task BatchQueryApiKeys(int batchSize, WhereDelegate<ApiKeyColumns> where, Action<IEnumerable<ApiHmacKey>> batchProcessor);
        Task BatchQueryApplications(int batchSize, WhereDelegate<ApplicationColumns> where, Action<IEnumerable<Data.Application>> batchProcessor);
        Task BatchQueryClients(int batchSize, WhereDelegate<ClientColumns> where, Action<IEnumerable<Data.Client>> batchProcessor);
        Task BatchQueryClientServerConnections(int batchSize, WhereDelegate<ClientServerConnectionColumns> where, Action<IEnumerable<Data.ClientServerConnection>> batchProcessor);
        Task BatchQueryConfigurations(int batchSize, WhereDelegate<ConfigurationColumns> where, Action<IEnumerable<Data.Configuration>> batchProcessor);
        Task BatchQueryConfigurationSettings(int batchSize, WhereDelegate<ConfigurationSettingColumns> where, Action<IEnumerable<Data.ConfigurationSetting>> batchProcessor);
        Task BatchQueryHostAddresses(int batchSize, WhereDelegate<HostAddressColumns> where, Action<IEnumerable<Data.HostAddress>> batchProcessor);
        Task BatchQueryHostDomains(int batchSize, WhereDelegate<HostDomainColumns> where, Action<IEnumerable<Data.HostDomain>> batchProcessor);
        Task BatchQueryMachines(int batchSize, WhereDelegate<MachineColumns> where, Action<IEnumerable<Data.Machine>> batchProcessor);
        Task BatchQueryNics(int batchSize, WhereDelegate<NicColumns> where, Action<IEnumerable<Data.Nic>> batchProcessor);
        Task BatchQueryOrganizations(int batchSize, WhereDelegate<OrganizationColumns> where, Action<IEnumerable<Data.Organization>> batchProcessor);
        Task BatchQueryProcessDescriptors(int batchSize, WhereDelegate<ProcessDescriptorColumns> where, Action<IEnumerable<Data.ProcessDescriptor>> batchProcessor);
        Task BatchQuerySubscriptions(int batchSize, WhereDelegate<SubscriptionColumns> where, Action<IEnumerable<Data.Subscription>> batchProcessor);
        Task BatchQueryUsers(int batchSize, WhereDelegate<UserColumns> where, Action<IEnumerable<Data.User>> batchProcessor);
        Task BatchQueryUserSettings(int batchSize, WhereDelegate<UserSettingColumns> where, Action<IEnumerable<Data.UserSetting>> batchProcessor);
        IEnumerable<Data.ClientServerConnection> ClientServerConnectionsWhere(WhereDelegate<ClientServerConnectionColumns> where, OrderBy<ClientServerConnectionColumns> orderBy = null);
        IEnumerable<Data.Client> ClientsWhere(WhereDelegate<ClientColumns> where, OrderBy<ClientColumns> orderBy = null);
        IEnumerable<Data.ConfigurationSetting> ConfigurationSettingsWhere(WhereDelegate<ConfigurationSettingColumns> where, OrderBy<ConfigurationSettingColumns> orderBy = null);
        IEnumerable<Data.Configuration> ConfigurationsWhere(WhereDelegate<ConfigurationColumns> where, OrderBy<ConfigurationColumns> orderBy = null);
        long CountActiveApiKeyIndexs();
        long CountActiveApiKeyIndexsWhere(WhereDelegate<ActiveApiKeyIndexColumns> where);
        long CountApiKeys();
        long CountApiKeysWhere(WhereDelegate<ApiKeyColumns> where);
        long CountApplications();
        long CountApplicationsWhere(WhereDelegate<ApplicationColumns> where);
        long CountClients();
        long CountClientServerConnections();
        long CountClientServerConnectionsWhere(WhereDelegate<ClientServerConnectionColumns> where);
        long CountClientsWhere(WhereDelegate<ClientColumns> where);
        long CountConfigurations();
        long CountConfigurationSettings();
        long CountConfigurationSettingsWhere(WhereDelegate<ConfigurationSettingColumns> where);
        long CountConfigurationsWhere(WhereDelegate<ConfigurationColumns> where);
        long CountHostAddresses();
        long CountHostAddressesWhere(WhereDelegate<HostAddressColumns> where);
        long CountHostDomains();
        long CountHostDomainsWhere(WhereDelegate<HostDomainColumns> where);
        long CountMachines();
        long CountMachinesWhere(WhereDelegate<MachineColumns> where);
        long CountNics();
        long CountNicsWhere(WhereDelegate<NicColumns> where);
        long CountOrganizations();
        long CountOrganizationsWhere(WhereDelegate<OrganizationColumns> where);
        long CountProcessDescriptors();
        long CountProcessDescriptorsWhere(WhereDelegate<ProcessDescriptorColumns> where);
        long CountSubscriptions();
        long CountSubscriptionsWhere(WhereDelegate<SubscriptionColumns> where);
        long CountUsers();
        long CountUserSettings();
        long CountUserSettingsWhere(WhereDelegate<UserSettingColumns> where);
        long CountUsersWhere(WhereDelegate<UserColumns> where);
        ActiveApiSigningKeyIndex GetOneActiveApiKeyIndexWhere(WhereDelegate<ActiveApiKeyIndexColumns> where);
        ApiHmacKey GetOneApiKeyWhere(WhereDelegate<ApiKeyColumns> where);
        Data.Application GetOneApplicationWhere(WhereDelegate<ApplicationColumns> where);
        Data.ClientServerConnection GetOneClientServerConnectionWhere(WhereDelegate<ClientServerConnectionColumns> where);
        Data.Client GetOneClientWhere(WhereDelegate<ClientColumns> where);
        Data.ConfigurationSetting GetOneConfigurationSettingWhere(WhereDelegate<ConfigurationSettingColumns> where);
        Data.Configuration GetOneConfigurationWhere(WhereDelegate<ConfigurationColumns> where);
        Data.HostAddress GetOneHostAddressWhere(WhereDelegate<HostAddressColumns> where);
        Data.HostDomain GetOneHostDomainWhere(WhereDelegate<HostDomainColumns> where);
        Data.Machine GetOneMachineWhere(WhereDelegate<MachineColumns> where);
        Data.Nic GetOneNicWhere(WhereDelegate<NicColumns> where);
        Data.Organization GetOneOrganizationWhere(WhereDelegate<OrganizationColumns> where);
        Data.ProcessDescriptor GetOneProcessDescriptorWhere(WhereDelegate<ProcessDescriptorColumns> where);
        Data.Subscription GetOneSubscriptionWhere(WhereDelegate<SubscriptionColumns> where);
        Data.UserSetting GetOneUserSettingWhere(WhereDelegate<UserSettingColumns> where);
        Data.User GetOneUserWhere(WhereDelegate<UserColumns> where);
        IEnumerable<Data.HostAddress> HostAddressesWhere(WhereDelegate<HostAddressColumns> where, OrderBy<HostAddressColumns> orderBy = null);
        IEnumerable<Data.HostDomain> HostDomainsWhere(WhereDelegate<HostDomainColumns> where, OrderBy<HostDomainColumns> orderBy = null);
        IEnumerable<Data.Machine> MachinesWhere(WhereDelegate<MachineColumns> where, OrderBy<MachineColumns> orderBy = null);
        IEnumerable<Data.Nic> NicsWhere(WhereDelegate<NicColumns> where, OrderBy<NicColumns> orderBy = null);
        ActiveApiSigningKeyIndex OneActiveApiKeyIndexWhere(WhereDelegate<ActiveApiKeyIndexColumns> where);
        ApiHmacKey OneApiKeyWhere(WhereDelegate<ApiKeyColumns> where);
        Data.Application OneApplicationWhere(WhereDelegate<ApplicationColumns> where);
        Data.ClientServerConnection OneClientServerConnectionWhere(WhereDelegate<ClientServerConnectionColumns> where);
        Data.Client OneClientWhere(WhereDelegate<ClientColumns> where);
        Data.ConfigurationSetting OneConfigurationSettingWhere(WhereDelegate<ConfigurationSettingColumns> where);
        Data.Configuration OneConfigurationWhere(WhereDelegate<ConfigurationColumns> where);
        Data.HostAddress OneHostAddressWhere(WhereDelegate<HostAddressColumns> where);
        Data.HostDomain OneHostDomainWhere(WhereDelegate<HostDomainColumns> where);
        Data.Machine OneMachineWhere(WhereDelegate<MachineColumns> where);
        Data.Nic OneNicWhere(WhereDelegate<NicColumns> where);
        Data.Organization OneOrganizationWhere(WhereDelegate<OrganizationColumns> where);
        Data.ProcessDescriptor OneProcessDescriptorWhere(WhereDelegate<ProcessDescriptorColumns> where);
        Data.Subscription OneSubscriptionWhere(WhereDelegate<SubscriptionColumns> where);
        Data.UserSetting OneUserSettingWhere(WhereDelegate<UserSettingColumns> where);
        Data.User OneUserWhere(WhereDelegate<UserColumns> where);
        IEnumerable<Data.Organization> OrganizationsWhere(WhereDelegate<OrganizationColumns> where, OrderBy<OrganizationColumns> orderBy = null);
        IEnumerable<Data.ProcessDescriptor> ProcessDescriptorsWhere(WhereDelegate<ProcessDescriptorColumns> where, OrderBy<ProcessDescriptorColumns> orderBy = null);
        void SetOneActiveApiKeyIndexWhere(WhereDelegate<ActiveApiKeyIndexColumns> where);
        void SetOneActiveApiKeyIndexWhere(WhereDelegate<ActiveApiKeyIndexColumns> where, out ActiveApiSigningKeyIndex result);
        void SetOneApiKeyWhere(WhereDelegate<ApiKeyColumns> where);
        void SetOneApiKeyWhere(WhereDelegate<ApiKeyColumns> where, out ApiHmacKey result);
        void SetOneApplicationWhere(WhereDelegate<ApplicationColumns> where);
        void SetOneApplicationWhere(WhereDelegate<ApplicationColumns> where, out Data.Application result);
        void SetOneClientServerConnectionWhere(WhereDelegate<ClientServerConnectionColumns> where);
        void SetOneClientServerConnectionWhere(WhereDelegate<ClientServerConnectionColumns> where, out Data.ClientServerConnection result);
        void SetOneClientWhere(WhereDelegate<ClientColumns> where);
        void SetOneClientWhere(WhereDelegate<ClientColumns> where, out Data.Client result);
        void SetOneConfigurationSettingWhere(WhereDelegate<ConfigurationSettingColumns> where);
        void SetOneConfigurationSettingWhere(WhereDelegate<ConfigurationSettingColumns> where, out Data.ConfigurationSetting result);
        void SetOneConfigurationWhere(WhereDelegate<ConfigurationColumns> where);
        void SetOneConfigurationWhere(WhereDelegate<ConfigurationColumns> where, out Data.Configuration result);
        void SetOneHostAddressWhere(WhereDelegate<HostAddressColumns> where);
        void SetOneHostAddressWhere(WhereDelegate<HostAddressColumns> where, out Data.HostAddress result);
        void SetOneHostDomainWhere(WhereDelegate<HostDomainColumns> where);
        void SetOneHostDomainWhere(WhereDelegate<HostDomainColumns> where, out Data.HostDomain result);
        void SetOneMachineWhere(WhereDelegate<MachineColumns> where);
        void SetOneMachineWhere(WhereDelegate<MachineColumns> where, out Data.Machine result);
        void SetOneNicWhere(WhereDelegate<NicColumns> where);
        void SetOneNicWhere(WhereDelegate<NicColumns> where, out Data.Nic result);
        void SetOneOrganizationWhere(WhereDelegate<OrganizationColumns> where);
        void SetOneOrganizationWhere(WhereDelegate<OrganizationColumns> where, out Data.Organization result);
        void SetOneProcessDescriptorWhere(WhereDelegate<ProcessDescriptorColumns> where);
        void SetOneProcessDescriptorWhere(WhereDelegate<ProcessDescriptorColumns> where, out Data.ProcessDescriptor result);
        void SetOneSubscriptionWhere(WhereDelegate<SubscriptionColumns> where);
        void SetOneSubscriptionWhere(WhereDelegate<SubscriptionColumns> where, out Data.Subscription result);
        void SetOneUserSettingWhere(WhereDelegate<UserSettingColumns> where);
        void SetOneUserSettingWhere(WhereDelegate<UserSettingColumns> where, out Data.UserSetting result);
        void SetOneUserWhere(WhereDelegate<UserColumns> where);
        void SetOneUserWhere(WhereDelegate<UserColumns> where, out Data.User result);
        IEnumerable<Data.Subscription> SubscriptionsWhere(WhereDelegate<SubscriptionColumns> where, OrderBy<SubscriptionColumns> orderBy = null);
        IEnumerable<ActiveApiSigningKeyIndex> TopActiveApiKeyIndexsWhere(int count, WhereDelegate<ActiveApiKeyIndexColumns> where);
        IEnumerable<ActiveApiSigningKeyIndex> TopActiveApiKeyIndexsWhere(int count, WhereDelegate<ActiveApiKeyIndexColumns> where, OrderBy<ActiveApiKeyIndexColumns> orderBy);
        IEnumerable<ApiHmacKey> TopApiKeysWhere(int count, WhereDelegate<ApiKeyColumns> where);
        IEnumerable<ApiHmacKey> TopApiKeysWhere(int count, WhereDelegate<ApiKeyColumns> where, OrderBy<ApiKeyColumns> orderBy);
        IEnumerable<Data.Application> TopApplicationsWhere(int count, WhereDelegate<ApplicationColumns> where);
        IEnumerable<Data.Application> TopApplicationsWhere(int count, WhereDelegate<ApplicationColumns> where, OrderBy<ApplicationColumns> orderBy);
        IEnumerable<Data.ClientServerConnection> TopClientServerConnectionsWhere(int count, WhereDelegate<ClientServerConnectionColumns> where);
        IEnumerable<Data.ClientServerConnection> TopClientServerConnectionsWhere(int count, WhereDelegate<ClientServerConnectionColumns> where, OrderBy<ClientServerConnectionColumns> orderBy);
        IEnumerable<Data.Client> TopClientsWhere(int count, WhereDelegate<ClientColumns> where);
        IEnumerable<Data.Client> TopClientsWhere(int count, WhereDelegate<ClientColumns> where, OrderBy<ClientColumns> orderBy);
        IEnumerable<Data.ConfigurationSetting> TopConfigurationSettingsWhere(int count, WhereDelegate<ConfigurationSettingColumns> where);
        IEnumerable<Data.ConfigurationSetting> TopConfigurationSettingsWhere(int count, WhereDelegate<ConfigurationSettingColumns> where, OrderBy<ConfigurationSettingColumns> orderBy);
        IEnumerable<Data.Configuration> TopConfigurationsWhere(int count, WhereDelegate<ConfigurationColumns> where);
        IEnumerable<Data.Configuration> TopConfigurationsWhere(int count, WhereDelegate<ConfigurationColumns> where, OrderBy<ConfigurationColumns> orderBy);
        IEnumerable<Data.HostAddress> TopHostAddressesWhere(int count, WhereDelegate<HostAddressColumns> where);
        IEnumerable<Data.HostAddress> TopHostAddressesWhere(int count, WhereDelegate<HostAddressColumns> where, OrderBy<HostAddressColumns> orderBy);
        IEnumerable<Data.HostDomain> TopHostDomainsWhere(int count, WhereDelegate<HostDomainColumns> where);
        IEnumerable<Data.HostDomain> TopHostDomainsWhere(int count, WhereDelegate<HostDomainColumns> where, OrderBy<HostDomainColumns> orderBy);
        IEnumerable<Data.Machine> TopMachinesWhere(int count, WhereDelegate<MachineColumns> where);
        IEnumerable<Data.Machine> TopMachinesWhere(int count, WhereDelegate<MachineColumns> where, OrderBy<MachineColumns> orderBy);
        IEnumerable<Data.Nic> TopNicsWhere(int count, WhereDelegate<NicColumns> where);
        IEnumerable<Data.Nic> TopNicsWhere(int count, WhereDelegate<NicColumns> where, OrderBy<NicColumns> orderBy);
        IEnumerable<Data.Organization> TopOrganizationsWhere(int count, WhereDelegate<OrganizationColumns> where);
        IEnumerable<Data.Organization> TopOrganizationsWhere(int count, WhereDelegate<OrganizationColumns> where, OrderBy<OrganizationColumns> orderBy);
        IEnumerable<Data.ProcessDescriptor> TopProcessDescriptorsWhere(int count, WhereDelegate<ProcessDescriptorColumns> where);
        IEnumerable<Data.ProcessDescriptor> TopProcessDescriptorsWhere(int count, WhereDelegate<ProcessDescriptorColumns> where, OrderBy<ProcessDescriptorColumns> orderBy);
        IEnumerable<Data.Subscription> TopSubscriptionsWhere(int count, WhereDelegate<SubscriptionColumns> where);
        IEnumerable<Data.Subscription> TopSubscriptionsWhere(int count, WhereDelegate<SubscriptionColumns> where, OrderBy<SubscriptionColumns> orderBy);
        IEnumerable<Data.UserSetting> TopUserSettingsWhere(int count, WhereDelegate<UserSettingColumns> where);
        IEnumerable<Data.UserSetting> TopUserSettingsWhere(int count, WhereDelegate<UserSettingColumns> where, OrderBy<UserSettingColumns> orderBy);
        IEnumerable<Data.User> TopUsersWhere(int count, WhereDelegate<UserColumns> where);
        IEnumerable<Data.User> TopUsersWhere(int count, WhereDelegate<UserColumns> where, OrderBy<UserColumns> orderBy);
        IEnumerable<Data.UserSetting> UserSettingsWhere(WhereDelegate<UserSettingColumns> where, OrderBy<UserSettingColumns> orderBy = null);
        IEnumerable<Data.User> UsersWhere(WhereDelegate<UserColumns> where, OrderBy<UserColumns> orderBy = null);
    }
}